import * as THREE from 'three';
export type TreeKind = 'oak' | 'redwood' | 'palm' | 'cypress';
export declare function createTree(kind: TreeKind, scale?: number, seed?: string): THREE.Group;
export declare function createCar(color: number, robotaxi?: boolean): THREE.Group;
export declare function createDeliveryBot(seed: string): THREE.Group;
export declare function createBoat(kind: 'sail' | 'ferry' | 'speed', accent: number): THREE.Group;
export declare function createBlimp(texture: THREE.CanvasTexture): THREE.Group;
export declare function createHotAirBalloon(): THREE.Group;
export declare function createHvacUnit(scale?: number): THREE.Group;
export declare function createWaterTank(scale?: number): THREE.Group;
export declare function createSolarArray(cols: number, rows: number): THREE.Group;
export declare function createAntennaMast(height: number, color: number): THREE.Group;
export declare function createWorldSign(lines: string[], style: 'cardboard' | 'banner' | 'neon' | 'caution', width?: number, height?: number, postHeight?: number): THREE.Group;
export declare function createPizzaBoxStack(count: number, seed: string): THREE.Group;
export declare function createBeanBag(color: number): THREE.Mesh;
export declare function createPingPongTable(): THREE.Group;
export declare function createKombuchaKeg(): THREE.Group;
export declare function createFoodTruck(color: number, seed: string): THREE.Group;
export declare function createIpoBell(): THREE.Group;
export declare function createTumbleweed(scale?: number): THREE.Mesh;
export declare function createCrow(): THREE.Group;
export declare function createCrane(height: number, color?: number): THREE.Group;
export declare function createStreetLamp(): THREE.Group;
export declare function createPony(): THREE.Group;
export declare function createSteamPuff(scale: number): THREE.Sprite;
